### ISSUE TITLE
Doesn't seem to use all available cores

### ISSUE THREAD

**Issue by bsouthga** [motiz88/flow-docker#1]
Hi -- Thanks for making this repo!

I'm semi-new to docker, so my issue may be a result of that, but it doesn't seem like docker is utilizing all cores for flow (so starting a server / checking takes ~ 10 minutes instead of ~30seconds).

My setup:
- OSX 10.10.5
- Docker toolbox @1.9.0

I start the container with the following...

``` shell
docker run --rm -it -v $(pwd):/app motiz88/flow bash
```

Which works great. I then run `flow` which also works, but seems to only use 1 / 8 cores.

Any pointers? Thanks again :+1:

**Comment by jeffmo** [comment]
By default flow will use the min of either the number or processors (as returned by `nproc`) or the `server.max_workers` value that you may set in your config (if you set it).

I know just about nothing about docker (only saw your message over in #flowtype and came across this issue as a result), but what does `nproc` output in your container?

**Comment by bsouthga** [comment]
thanks for the speedy reply.

This is what I get...

``` shell
docker run --rm -it -v $(pwd):/app motiz88/flow:0.17.0 bash
root@e4e5444af68d:/app# nproc
1
```

guess I need to figure out how to get docker to use more cores?

**Comment by jeffmo** [comment]
There's the issue then I suppose... :) It looks like whatever process you (and flow) are running in probably has a limit of 1...

Is there a way to tune the ulimits for your container maybe? A quick google search turned this up which seems like it might be related? https://github.com/docker/docker/issues/12695

**Comment by bsouthga** [comment]
I'll take a peek! thanks again, flow is great btw doing a talk tomorrow at my company about why we should use it in development!

**Comment by jeffmo** [comment]
awesome! :)

**Comment by bsouthga** [comment]
looks like the issue was that `docker-machine` defaults to one core on startup, after manually creating a new docker environment with...

``` shell
docker-machine create --virtualbox-cpu-count 4 --virtualbox-memory 4096 --driver virtualbox dev
```

the cores are available!
