### ISSUE TITLE
Update to recent 0.24.* versions

### ISSUE THREAD

**Issue by avaly** [motiz88/flow-docker#2]
Please update with latest 0.24.\* versions

**Comment by MoOx** [comment]
@motiz88 do you need any help?
I am really new to docker (don't really use it) and work on OS X, but I will have to works with people that have Windows machine, so this project is my best shot.

Maybe you could give hints on how to make a PR for a new version?

**Comment by avaly** [comment]
I've sent a PR for all recent versions: #3

**Comment by MoOx** [comment]
Thanks!
